//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ini;
using System.IO;

namespace VALManager2015
{

    public class Aerolinea
    {
        private IniFile AerolineaCfg;
        
        private int id
        {
            get;
            set;
        }

        private string pathCfgFile
        {
            get;
            set;
        }

        private string nombre
        {
            get;
            set;
        }

        private string codigo
        {
            get;
            set;
        }

        private string pathLogoFile
        {
            get;
            set;
        }

        private string hashCode
        {
            get;
            set;
        }

        private int failPercent
        {
            get;
            set;
        }

        /// <summary>
        /// Constructor
        /// </summary>
        public Aerolinea()
        {
            var cfgFile = Path.Combine(Program.Caminos.airlineProfileDirectory, Program.activeAirline + ".ini");
            AerolineaCfg = new IniFile(cfgFile);
        }


        public void ReadCfgFile()
        {
            nombre = AerolineaCfg.IniReadValue("GENERAL", "NAME");
            codigo = AerolineaCfg.IniReadValue("GENERAL", "CODE");
            pathLogoFile = AerolineaCfg.IniReadValue("GENERAL", "PATHLOGOFILE");
            hashCode = AerolineaCfg.IniReadValue("GENERAL", "HASHCODE");
            failPercent = Convert.ToInt32(AerolineaCfg.IniReadValue("FAIL", "MARGIN"));
        }
    }
}

