//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace VALManager2015
{

    public class Airport
    {
        private int id { get; set; }

        private string icao { get; set; }

        private string iata { get; set; }

        private string longitud { get; set; }

        private string latitud { get; set; }

        private int idCiudad { get; set; }

        private int idPais { get; set; }

        private string Nombre { get; set; }

        private int altura { get; set; }

        private Decimal varMagnetica { get; set; }

        /// <summary>
        /// Array
        /// </summary>
        private int[] idPistas { get; set; }

        private int idEstado { get; set; }

    }
}

