//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace VALManager2015
{

    public class AvionApu
    {
        private TimeSpan horas { get; set; }

        private int id { get; set; }

        private bool needMantenimiento { get; set; }

        private Decimal indiceDesgaste { get; set; }

    }
}

