//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace VALManager2015
{

    public class Avion
    {
        private int id { get; set; }

        private FabricanteAvion fabricanteAvion { get; set; }

        private FlotaAvion flota { get; set; }

        private TimeSpan horasVuelo { get; set; }

        private AvionModelo modelo { get; set; }

    }
}

