//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace VALManager2015
{

    public class AvionMatricula
    {
        private int id { get; set; }

        private Avion avion { get; set; }

        private string matricula { get; set; }

        private ConfiguracionPaxAvion[] configuracionPaxAvion { get; set; }

        private ConfiguracionCargaAvion[] configuracionCargaAvion { get; set; }

        private AvionMotor[] avionMotor { get; set; }

        private AvionApu avionApu { get; set; }

        private Decimal landingWeight { get; set; }

        private Decimal maxLandingWeight { get; set; }

        private Decimal takeOffWeight { get; set; }

        private Decimal maxTakeOffWeight { get; set; }

        private AvionCategoria avionCategoria { get; set; }

        private AvionFlap[] avionFlap { get; set; }

        private AvionTren[] avionTren { get; set; }

        private AvionBateria[] avionBateria { get; set; }

        public virtual ConfiguracionAvion configuracionAvion { get; set; }

    }
}

