//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ini;

namespace VALManager2015
{

    public class Configuracion
    {

        IniFile systemCfgFile = new IniFile(Program.Caminos.systemCfg);

        private int idFs
        {
            get;
            set;
        }

        private int idAerolinea
        {
            get;
            set;
        }

        private string pathCfgFile
        {
            get;
            set;
        }

        private int id
        {
            get;
            set;
        }

        public Configuracion()
        {
            ReadCfgFile();
        }

        public void ReadCfgFile()
        {
            Program.Caminos.fsPath = systemCfgFile.IniReadValue("PATH", "FSPATH");
            Program.activeAirline = systemCfgFile.IniReadValue("AIRLINE", "NAME");
        }
    }
}

