//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ConfiguracionPaxAvion
{
	private int id
	{
		get;
		set;
	}

	private ConfiguracionAvion configuracion
	{
		get;
		set;
	}

	private int paxEstacionName
	{
		get;
		set;
	}

	private Decimal paxEstacionWeight
	{
		get;
		set;
	}

	private int paxEstacionNumeroDePax
	{
		get;
		set;
	}

	private int paxMaxNumero
	{
		get;
		set;
	}

	private Decimal paxMaxWeight
	{
		get;
		set;
	}

}

