//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ConfiguracionCargaAvion
{
	private int id
	{
		get;
		set;
	}

	private Decimal cargoWeight
	{
		get;
		set;
	}

	private string cargoName
	{
		get;
		set;
	}

	private Decimal cargoMaxWeight
	{
		get;
		set;
	}

}

