//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Serialization;
using System.Xml;
using System.IO;


namespace VALManager2015
{

    public class Configuracion
    {

        private FS _fs;
        private string _connectionModule;
        private string _aerolinea;


        public FS Fs
        {
            get { return _fs; }
            set { _fs = value; }
        }

        public string ConnectionModule
        {
            get { return _connectionModule; }
            set { _connectionModule = value; }
        }

        public string Aerolinea
        {
            get { return _aerolinea; }
            set { _aerolinea = value; }
        }

        public Configuracion()
        {
            _fs = new FS();
        }

        public void SaveDataToXml(string xmlFileName)
        {
            XmlSerializer serializer = new XmlSerializer(typeof(Configuracion));
            TextWriter writer = new StreamWriter(xmlFileName);
            serializer.Serialize(writer, this);
            writer.Close();
        }

        public void ReadCfgFileXml(string xmlFileName)
        {
            if (File.Exists(xmlFileName))
            {
                XmlSerializer serializer = new XmlSerializer(typeof(Configuracion));
                using (FileStream fs = new FileStream(xmlFileName, FileMode.Open))
                {
                    Configuracion _config;
                    _config = (Configuracion)serializer.Deserialize(fs);
                    Fs = _config.Fs;
                    ConnectionModule = _config.ConnectionModule;
                    Aerolinea = _config.Aerolinea;
                }
            }
        }

    }
}

