//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ConnectionModule
{
	private int id
	{
		get;
		set;
	}

	private string module
	{
		get;
		set;
	}

	private string pathModule
	{
		get;
		set;
	}

    public void SetModuleName(string name)
    {
        module = name;
    }

    public string GetModuleName()
    {
        return module;
    }

    public void SetPathModule(string path)
    {
        pathModule = path;
    }

    public string GetPathModule()
    {
        return pathModule;
    }
}

