//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


public class ConnectionModule
{
    private string _moduleName;
    private string _modulePath;

	public string ModuleName
	{
        get { return _moduleName; }
        set { _moduleName = value; }
	}

	public string ModulePath
	{
        get { return _modulePath; }
        set { _modulePath = value; }
	}

}

