//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class EventoVuelo
{
	private int id
	{
		get;
		set;
	}

	private string evento
	{
		get;
		set;
	}

	private string horaEvento
	{
		get;
		set;
	}

	private string alturaEvento
	{
		get;
		set;
	}

	private string velocidadEvento
	{
		get;
		set;
	}

	private string latitudEvento
	{
		get;
		set;
	}

	private string longitudEvento
	{
		get;
		set;
	}

}

