//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class FS
{
	private int id
	{
		get;
		set;
	}

	private string nombre
	{
		get;
		set;
	}

	private string path
	{
		get;
		set;
	}

	private ConnectionModule connectionModule
	{
		get;
		set;
	}

    public void SetNombre(string value)
    {
        nombre = value;
    }

    public void SetPath(string value)
    {
        path = value;
    }

    public string GetNombre()
    {
        return nombre;
    }

    public string GetPath()
    {
        return path;
    }

    public void SetConnectionModule(ConnectionModule cm)
    {
        connectionModule = cm;
    }

    public ConnectionModule GetConnectionModule()
    {
        return connectionModule;
    }
}

