//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


public class FS
{
    private string _nombre;
    private string _path;
    private ConnectionModule _connectionModule;

	public string Nombre
	{
        get { return _nombre; }
        set { _nombre = value; }
	}

	public string Path
	{
        get { return _path; }
        set { _path = value; }
	}

	public ConnectionModule ConnectionModule
	{
        get { return _connectionModule; }
        set { _connectionModule = value; }
	}

    public FS()
    {
        _connectionModule = new ConnectionModule();
    }
 }

