//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Itinerario
{
	private int id
	{
		get;
		set;
	}

	private int idAirportOrigen
	{
		get;
		set;
	}

	private int idAirportDestino
	{
		get;
		set;
	}

	private string etd
	{
		get;
		set;
	}

	private string ruta
	{
		get;
		set;
	}

	private string observaciones
	{
		get;
		set;
	}

	private string numero
	{
		get;
		set;
	}

	private bool isItinerante
	{
		get;
		set;
	}

	private bool isSimulador
	{
		get;
		set;
	}

	private bool isEspecial
	{
		get;
		set;
	}

}

