//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace VALManager2015
{

    public class PilotoExamen
    {
        private int id { get; set; }

        private ExamenPiloto examen { get; set; }

        private Piloto examinador { get; set; }

        private CalificacionExamenPiloto calificacion { get; set; }

        private DateTime fecha { get; set; }

        private string observaciones { get; set; }

    }
}

