//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace VALManager2015
{

    public class PilotoExamen
    {
        private Examen _examen;
        private string _examinador;
        private DateTime _fecha;
        private string _observaciones;

        public Examen Examen
        {
            get { return _examen; }
            set { _examen = value; }
        }

        public string _examinador
        {
            get { return _examinador; }
            set { _examinador = value; }
        }

        public DateTime Fecha
        {
            get { return _fecha; }
            set { _fecha = value; }
        }

        public string Observaciones
        {
            get { return _observaciones; }
            set { _observaciones = value; }
        }
    }
}

