//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Pistas
{
	private int id
	{
		get;
		set;
	}

	private string numero
	{
		get;
		set;
	}

	private Decimal largo
	{
		get;
		set;
	}

	private Decimal Heading
	{
		get;
		set;
	}

	private string longitud
	{
		get;
		set;
	}

	private string latitud
	{
		get;
		set;
	}

	private int idTipoPista
	{
		get;
		set;
	}

	private Decimal ilsFrecuencia
	{
		get;
		set;
	}

	private int ilsHeading
	{
		get;
		set;
	}

}

