//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PlanVuelo
{
	private int id
	{
		get;
		set;
	}

	private int idItinerario
	{
		get;
		set;
	}

	private int idFallo
	{
		get;
		set;
	}

	private int idPiloto
	{
		get;
		set;
	}

	/// <summary>
	/// Array que contiene todos los notams para este PV
	/// </summary>
	private int idVueloNotam
	{
		get;
		set;
	}

	private string alturaCrucero
	{
		get;
		set;
	}

	private string velocidadCrucero
	{
		get;
		set;
	}

	private string ruta
	{
		get;
		set;
	}

	private int idMatricula
	{
		get;
		set;
	}

}

