//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class VariableVuelo
{
	private int id
	{
		get;
		set;
	}

	private string origen
	{
		get;
		set;
	}

	private string destino
	{
		get;
		set;
	}

	private string tiempoSalida
	{
		get;
		set;
	}

	private string tiempoLlegada
	{
		get;
		set;
	}

	private string velocidadVertical
	{
		get;
		set;
	}

	private string tiempoVuelo
	{
		get;
		set;
	}

	private string tiempoDespegue
	{
		get;
		set;
	}

	private string tiempoAterrizaje
	{
		get;
		set;
	}

	private string fuelSalida
	{
		get;
		set;
	}

	private string fuelLlegada
	{
		get;
		set;
	}

	private string fuelDespegue
	{
		get;
		set;
	}

	private string fuelAterrizaje
	{
		get;
		set;
	}

	private string tiempoTotal
	{
		get;
		set;
	}

	/// <summary>
	/// Array con todos los eventos de este vuelo
	/// </summary>
	private int idEventoVuelo
	{
		get;
		set;
	}

	private string alturaCrucero
	{
		get;
		set;
	}

}

